# Site settings
title: 낭만검객
email: cybaek@me.com
description: > # this means to ignore newlines until "baseurl:"
    NHN Entertainment에서 '재밌는 일'을 하고 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cybaek.com" # the base hostname & protocol for your site
#twitter_username: cybaek
#github_username:  cybaek

# Build settings
markdown: kramdown
highlighter: pygments

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
